//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MissionPlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _01_01 {
            get {
                object obj = ResourceManager.GetObject("_01_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _01_03 {
            get {
                object obj = ResourceManager.GetObject("_01_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _01_05 {
            get {
                object obj = ResourceManager.GetObject("_01_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _01_06 {
            get {
                object obj = ResourceManager.GetObject("_01_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _0d92fed790a3a70170e61a86db103f399a595c70 {
            get {
                object obj = ResourceManager.GetObject("0d92fed790a3a70170e61a86db103f399a595c70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap airspeed {
            get {
                object obj = ResourceManager.GetObject("airspeed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Antenna_Tracker_01 {
            get {
                object obj = ResourceManager.GetObject("Antenna Tracker-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap APM_airframes_001 {
            get {
                object obj = ResourceManager.GetObject("APM_airframes_001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap APM_airframes_002 {
            get {
                object obj = ResourceManager.GetObject("APM_airframes_002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap APM_airframes_07 {
            get {
                object obj = ResourceManager.GetObject("APM_airframes_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap APM_airframes_08 {
            get {
                object obj = ResourceManager.GetObject("APM_airframes_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap APM_rover_firmware {
            get {
                object obj = ResourceManager.GetObject("APM_rover_firmware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apm1 {
            get {
                object obj = ResourceManager.GetObject("apm1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apm2 {
            get {
                object obj = ResourceManager.GetObject("apm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apm2_5 {
            get {
                object obj = ResourceManager.GetObject("apm2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp1 {
            get {
                object obj = ResourceManager.GetObject("apmp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp2 {
            get {
                object obj = ResourceManager.GetObject("apmp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp3 {
            get {
                object obj = ResourceManager.GetObject("apmp3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp4 {
            get {
                object obj = ResourceManager.GetObject("apmp4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp5 {
            get {
                object obj = ResourceManager.GetObject("apmp5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap apmp6 {
            get {
                object obj = ResourceManager.GetObject("apmp6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap attocurrent {
            get {
                object obj = ResourceManager.GetObject("attocurrent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bgdark {
            get {
                object obj = ResourceManager.GetObject("bgdark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap boat {
            get {
                object obj = ResourceManager.GetObject("boat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.733079 0.679631 -0.026393
        ///outer loop
        ///vertex -500.616943 -205.000000 101.222382
        ///vertex -500.887329 -205.307068 100.826370
        ///vertex -501.000946 -205.414169 101.224457
        ///endloop
        ///endfacet
        ///facet normal -0.787530 0.613381 -0.059672
        ///outer loop
        ///vertex -501.000946 -205.414169 101.224457
        ///vertex -500.887329 -205.307068 100.826370
        ///vertex -501.113586 -205.631546 100.476418
        ///endloop
        ///endfacet
        ///facet normal -0.777142 0.625975 -0.064857
        ///outer loop
        ///vertex -501.000[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string boat_stl {
            get {
                return ResourceManager.GetString("boat_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BR_APMPWRDEAN_2 {
            get {
                object obj = ResourceManager.GetObject("BR-APMPWRDEAN-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BT_hc06 {
            get {
                object obj = ResourceManager.GetObject("BT-hc06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration01 {
            get {
                object obj = ResourceManager.GetObject("calibration01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration02 {
            get {
                object obj = ResourceManager.GetObject("calibration02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration03 {
            get {
                object obj = ResourceManager.GetObject("calibration03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration04 {
            get {
                object obj = ResourceManager.GetObject("calibration04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration05 {
            get {
                object obj = ResourceManager.GetObject("calibration05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration06 {
            get {
                object obj = ResourceManager.GetObject("calibration06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap calibration07 {
            get {
                object obj = ResourceManager.GetObject("calibration07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap camera_icon {
            get {
                object obj = ResourceManager.GetObject("camera_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap camera_icon_G {
            get {
                object obj = ResourceManager.GetObject("camera_icon_G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameraGimalPitch1 {
            get {
                object obj = ResourceManager.GetObject("cameraGimalPitch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameraGimalRoll1 {
            get {
                object obj = ResourceManager.GetObject("cameraGimalRoll1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameraGimalYaw {
            get {
                object obj = ResourceManager.GetObject("cameraGimalYaw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string coaxial_stl {
            get {
                return ResourceManager.GetString("coaxial_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string copter_stl {
            get {
                return ResourceManager.GetString("copter_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_connect_icon {
            get {
                object obj = ResourceManager.GetObject("dark_connect_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_disconnect_icon {
            get {
                object obj = ResourceManager.GetObject("dark_disconnect_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_flightdata_icon {
            get {
                object obj = ResourceManager.GetObject("dark_flightdata_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_flightplan_icon {
            get {
                object obj = ResourceManager.GetObject("dark_flightplan_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_help_icon {
            get {
                object obj = ResourceManager.GetObject("dark_help_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_initialsetup_icon {
            get {
                object obj = ResourceManager.GetObject("dark_initialsetup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_simulation_icon {
            get {
                object obj = ResourceManager.GetObject("dark_simulation_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_terminal_icon {
            get {
                object obj = ResourceManager.GetObject("dark_terminal_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap dark_tuningconfig_icon {
            get {
                object obj = ResourceManager.GetObject("dark_tuningconfig_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string dodecarotor_stl {
            get {
                return ResourceManager.GetString("dodecarotor_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap donate {
            get {
                object obj = ResourceManager.GetObject("donate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap frames_06 {
            get {
                object obj = ResourceManager.GetObject("frames_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap frames_h {
            get {
                object obj = ResourceManager.GetObject("frames-h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap frames_plus {
            get {
                object obj = ResourceManager.GetObject("frames_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap frames_x {
            get {
                object obj = ResourceManager.GetObject("frames_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_01 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_011 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_012 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_02 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_03 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_04 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_05 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_06 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_07 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_08 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_09 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_10 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_11 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_12 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_13 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_14 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_15 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap FW_icons_2013_logos_16 {
            get {
                object obj = ResourceManager.GetObject("FW icons 2013+logos-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Gaugebg {
            get {
                object obj = ResourceManager.GetObject("Gaugebg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gps {
            get {
                object obj = ResourceManager.GetObject("gps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gps_light {
            get {
                object obj = ResourceManager.GetObject("gps_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap heli {
            get {
                object obj = ResourceManager.GetObject("heli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal 0.105252 -0.703177 -0.703181
        ///outer loop
        ///vertex 170.696533 -71.619972 -17.210230
        ///vertex 170.696518 -69.729424 -19.100780
        ///vertex 518.093506 -23.088806 -13.743027
        ///endloop
        ///endfacet
        ///facet normal 0.105251 -0.703176 -0.703183
        ///outer loop
        ///vertex 170.696533 -71.619972 -17.210230
        ///vertex 518.093506 -23.088806 -13.743027
        ///vertex 518.093506 -24.979355 -11.852502
        ///endloop
        ///endfacet
        ///facet normal -0.049585 0.258507 0.964736
        ///outer loop
        ///vertex 518.093506 -20.506304[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string helicopter_stl {
            get {
                return ResourceManager.GetString("helicopter_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {\rtf1\ansi\ansicpg1252\deff0\deflang3081\deflangfe3081{\fonttbl{\f0\fswiss\fprq2\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\nowidctlpar\sa200\sl276\slmult1\f0\fs22\par
        ///\tab Welcome to the \b Mission Planner\b0 , mission planning for Unmanned Aerial Vehicles (\b UAV\b0 ).\par
        ///\pard\nowidctlpar\fi720\b Help:\par
        ///Arduplane: {\field{\*\fldinst{HYPERLINK &quot;http://ardupilot.org/plane&quot;}}{\fldrslt{\ul\cf1 http://ardupilot.org/plane}}}\f0\fs2[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string help_text {
            get {
                return ResourceManager.GetString("help_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hexa {
            get {
                object obj = ResourceManager.GetObject("hexa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string hexarotor_stl {
            get {
                return ResourceManager.GetString("hexarotor_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Hframe {
            get {
                object obj = ResourceManager.GetObject("Hframe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Hframelight {
            get {
                object obj = ResourceManager.GetObject("Hframelight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hil {
            get {
                object obj = ResourceManager.GetObject("hil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hilheli {
            get {
                object obj = ResourceManager.GetObject("hilheli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hilplane {
            get {
                object obj = ResourceManager.GetObject("hilplane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hilquad {
            get {
                object obj = ResourceManager.GetObject("hilquad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_config {
            get {
                object obj = ResourceManager.GetObject("icon_config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_fly {
            get {
                object obj = ResourceManager.GetObject("icon_fly", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_plan {
            get {
                object obj = ResourceManager.GetObject("icon_plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_setup {
            get {
                object obj = ResourceManager.GetObject("icon_setup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap icon_sitl {
            get {
                object obj = ResourceManager.GetObject("icon_sitl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconWarning32 {
            get {
                object obj = ResourceManager.GetObject("iconWarning32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap iconWarning48 {
            get {
                object obj = ResourceManager.GetObject("iconWarning48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_01 {
            get {
                object obj = ResourceManager.GetObject("light_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_03 {
            get {
                object obj = ResourceManager.GetObject("light_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_05 {
            get {
                object obj = ResourceManager.GetObject("light_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_06 {
            get {
                object obj = ResourceManager.GetObject("light_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_connect_icon {
            get {
                object obj = ResourceManager.GetObject("light_connect_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_disconnect_icon {
            get {
                object obj = ResourceManager.GetObject("light_disconnect_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_flightdata_icon {
            get {
                object obj = ResourceManager.GetObject("light_flightdata_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_flightplan_icon {
            get {
                object obj = ResourceManager.GetObject("light_flightplan_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_help_icon {
            get {
                object obj = ResourceManager.GetObject("light_help_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_initialsetup_icon {
            get {
                object obj = ResourceManager.GetObject("light_initialsetup_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_simulation_icon {
            get {
                object obj = ResourceManager.GetObject("light_simulation_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_terminal_icon {
            get {
                object obj = ResourceManager.GetObject("light_terminal_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap light_tuningconfig_icon {
            get {
                object obj = ResourceManager.GetObject("light_tuningconfig_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap maggps {
            get {
                object obj = ResourceManager.GetObject("maggps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_01 {
            get {
                object obj = ResourceManager.GetObject("marker_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_02 {
            get {
                object obj = ResourceManager.GetObject("marker_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_03 {
            get {
                object obj = ResourceManager.GetObject("marker_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_04 {
            get {
                object obj = ResourceManager.GetObject("marker_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_05 {
            get {
                object obj = ResourceManager.GetObject("marker_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_06 {
            get {
                object obj = ResourceManager.GetObject("marker_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap marker_07 {
            get {
                object obj = ResourceManager.GetObject("marker_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///
        ///&lt;!-- TAGS ARE CASE SENSATIVE --&gt;
        ///&lt;CMD&gt;
        ///  &lt;AC2&gt;
        ///    &lt;WAYPOINT&gt;
        ///      &lt;P1&gt;Delay&lt;/P1&gt;
        ///      &lt;P2&gt;&lt;/P2&gt;
        ///      &lt;P3&gt;&lt;/P3&gt;
        ///      &lt;P4&gt;&lt;/P4&gt;
        ///      &lt;X&gt;Lat&lt;/X&gt;
        ///      &lt;Y&gt;Long&lt;/Y&gt;
        ///      &lt;Z unitType=&quot;alt&quot;&gt;Alt&lt;/Z&gt;
        ///    &lt;/WAYPOINT&gt;
        ///    &lt;TAKEOFF&gt;
        ///      &lt;P1&gt;&lt;/P1&gt;
        ///      &lt;P2&gt;&lt;/P2&gt;
        ///      &lt;P3&gt;&lt;/P3&gt;
        ///      &lt;P4&gt;&lt;/P4&gt;
        ///      &lt;X&gt;&lt;/X&gt;
        ///      &lt;Y&gt;&lt;/Y&gt;
        ///      &lt;Z unitType=&quot;alt&quot;&gt;Alt&lt;/Z&gt;
        ///    &lt;/TAKEOFF&gt;
        ///    &lt;RETURN_TO_LAUNCH&gt;
        ///      &lt;P1&gt;&lt;/P1&gt;
        ///      &lt;P2&gt;&lt;/P2&gt;
        ///      &lt;P3&gt;&lt;/P3&gt;
        ///      &lt;P4&gt;&lt;/P4&gt;
        ///      &lt;[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string mavcmd {
            get {
                return ResourceManager.GetString("mavcmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   == MAVLink Parameters == (this is a copy fo the wiki page FYI)
        ///
        ///This is a list of all the user-modifiable MAVLink parameters and what they do. You can modify them via the MAVLink parameters window in any compatible GCS, such as the Mission Planner, HK GCS or !QGroundControl.
        ///
        ///It includes both fixed wing (APM) and rotary wing (!ArduCopter) parameters. Some may only be relevant for one platform or another.
        ///
        ///|| *EEPROM variable name* || *Min* || *Max* || *Default* || *Multiplier* || *Enabled (0 = no, 1 =[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MAVParam {
            get {
                return ResourceManager.GetString("MAVParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MinimOSD {
            get {
                object obj = ResourceManager.GetObject("MinimOSD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap missionplannerlogo {
            get {
                object obj = ResourceManager.GetObject("missionplannerlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap missionplannerlogodark {
            get {
                object obj = ResourceManager.GetObject("missionplannerlogodark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon mpdesktop {
            get {
                object obj = ResourceManager.GetObject("mpdesktop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap new_3DR_04 {
            get {
                object obj = ResourceManager.GetObject("new-3DR-04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap no_video {
            get {
                object obj = ResourceManager.GetObject("no-video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap octo {
            get {
                object obj = ResourceManager.GetObject("octo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string octorotor_stl {
            get {
                return ResourceManager.GetString("octorotor_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap octov {
            get {
                object obj = ResourceManager.GetObject("octov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap octox {
            get {
                object obj = ResourceManager.GetObject("octox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap opticalflow {
            get {
                object obj = ResourceManager.GetObject("opticalflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Parachute {
            get {
                object obj = ResourceManager.GetObject("Parachute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pixhawk {
            get {
                object obj = ResourceManager.GetObject("pixhawk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pixhawk2cube {
            get {
                object obj = ResourceManager.GetObject("pixhawk2cube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.462529 0.886428 -0.017668
        ///outer loop
        ///vertex -82.253357 213.777756 40.570683
        ///vertex -82.550934 213.577362 38.306007
        ///vertex -83.475891 213.131821 40.167847
        ///endloop
        ///endfacet
        ///facet normal -0.969419 0.204115 -0.136250
        ///outer loop
        ///vertex -84.991020 208.326782 32.910004
        ///vertex -84.837891 209.806168 34.036636
        ///vertex -84.831329 207.866104 31.083696
        ///endloop
        ///endfacet
        ///facet normal -0.959343 0.280675 -0.029709
        ///outer loop
        ///vertex -84.988464 210.394073 38.7[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string plane_stl {
            get {
                return ResourceManager.GetString("plane_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planebackground {
            get {
                object obj = ResourceManager.GetObject("planebackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon {
            get {
                object obj = ResourceManager.GetObject("planeicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon1 {
            get {
                object obj = ResourceManager.GetObject("planeicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon2 {
            get {
                object obj = ResourceManager.GetObject("planeicon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon3 {
            get {
                object obj = ResourceManager.GetObject("planeicon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon4 {
            get {
                object obj = ResourceManager.GetObject("planeicon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon5 {
            get {
                object obj = ResourceManager.GetObject("planeicon5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap planeicon6 {
            get {
                object obj = ResourceManager.GetObject("planeicon6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFrames_02 {
            get {
                object obj = ResourceManager.GetObject("PlusFrames_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFrames_04 {
            get {
                object obj = ResourceManager.GetObject("PlusFrames_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFrames_06 {
            get {
                object obj = ResourceManager.GetObject("PlusFrames_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFramesGreen_02 {
            get {
                object obj = ResourceManager.GetObject("PlusFramesGreen_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFramesGreen_04 {
            get {
                object obj = ResourceManager.GetObject("PlusFramesGreen_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PlusFramesGreen_06 {
            get {
                object obj = ResourceManager.GetObject("PlusFramesGreen_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap px4 {
            get {
                object obj = ResourceManager.GetObject("px4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PX4FLOW1 {
            get {
                object obj = ResourceManager.GetObject("PX4FLOW1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quad {
            get {
                object obj = ResourceManager.GetObject("quad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_01 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_03 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_05 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_06 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_11 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_12 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadframesnormal_14 {
            get {
                object obj = ResourceManager.GetObject("quadframesnormal_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_01 {
            get {
                object obj = ResourceManager.GetObject("quadhover_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_03 {
            get {
                object obj = ResourceManager.GetObject("quadhover_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_05 {
            get {
                object obj = ResourceManager.GetObject("quadhover_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_06 {
            get {
                object obj = ResourceManager.GetObject("quadhover_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_11 {
            get {
                object obj = ResourceManager.GetObject("quadhover_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_12 {
            get {
                object obj = ResourceManager.GetObject("quadhover_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadhover_14 {
            get {
                object obj = ResourceManager.GetObject("quadhover_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadicon {
            get {
                object obj = ResourceManager.GetObject("quadicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.000623 -0.977013 -0.213179
        ///outer loop
        ///vertex 113.475410 -313.526215 35.304485
        ///vertex 124.658485 -313.900787 36.988503
        ///vertex 91.495171 -313.708649 36.204845
        ///endloop
        ///endfacet
        ///facet normal -0.645655 -0.757765 -0.094449
        ///outer loop
        ///vertex -50.196384 -313.013763 39.901405
        ///vertex -48.536770 -314.584625 41.159321
        ///vertex -49.934750 -313.374115 41.004070
        ///endloop
        ///endfacet
        ///facet normal -0.903891 -0.427101 -0.023771
        ///outer loop
        ///vertex -50.861809 -311.73[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string quadplane_stl {
            get {
                return ResourceManager.GetString("quadplane_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string quadrotor_stl {
            get {
                return ResourceManager.GetString("quadrotor_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap quadx {
            get {
                object obj = ResourceManager.GetObject("quadx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap redsinglecopter2 {
            get {
                object obj = ResourceManager.GetObject("redsinglecopter2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rover {
            get {
                object obj = ResourceManager.GetObject("rover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rover_10 {
            get {
                object obj = ResourceManager.GetObject("rover_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rover_11 {
            get {
                object obj = ResourceManager.GetObject("rover_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal 0.114214 -0.206677 -0.971720
        ///outer loop
        ///vertex -117.211578 -20.733070 20.369612
        ///vertex -117.211578 -18.569389 19.909412
        ///vertex -115.211578 -20.526741 20.560801
        ///endloop
        ///endfacet
        ///facet normal -0.169688 -0.462916 -0.870008
        ///outer loop
        ///vertex -115.211578 -20.526741 20.560801
        ///vertex -117.211578 -18.569389 19.909412
        ///vertex -115.211578 -18.241907 19.345085
        ///endloop
        ///endfacet
        ///facet normal 0.136919 -0.986723 -0.087350
        ///outer loop
        ///vertex -117.211578 -18.569[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string rover_stl {
            get {
                return ResourceManager.GetString("rover_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap selectvehicle {
            get {
                object obj = ResourceManager.GetObject("selectvehicle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Shutter {
            get {
                object obj = ResourceManager.GetObject("Shutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap sonar {
            get {
                object obj = ResourceManager.GetObject("sonar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap splashdark {
            get {
                object obj = ResourceManager.GetObject("splashdark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap sub {
            get {
                object obj = ResourceManager.GetObject("sub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal 0.000000 0.998618 0.052551
        ///outer loop
        ///vertex -148.527283 20.485769 261.991425
        ///vertex -123.527275 20.485769 261.991425
        ///vertex -148.527283 20.595785 259.900818
        ///endloop
        ///endfacet
        ///facet normal 0.000000 0.987724 0.156209
        ///outer loop
        ///vertex -148.527283 20.485769 261.991425
        ///vertex -148.527283 20.158773 264.059052
        ///vertex -123.527275 20.485769 261.991425
        ///endloop
        ///endfacet
        ///facet normal 0.000000 0.987724 0.156209
        ///outer loop
        ///vertex -123.527275 20.485769 261.[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sub_stl {
            get {
                return ResourceManager.GetString("sub_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap TD_MP {
            get {
                object obj = ResourceManager.GetObject("TD_MP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap TD_MP_light {
            get {
                object obj = ResourceManager.GetObject("TD_MP_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tri {
            get {
                object obj = ResourceManager.GetObject("tri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   solid Exported from Blender-3.6.22
        ///facet normal -0.469899 0.529200 -0.706500
        ///outer loop
        ///vertex 130.948959 123.188995 40.020233
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 130.595413 123.542564 40.520229
        ///endloop
        ///endfacet
        ///facet normal -0.452574 0.531558 -0.715977
        ///outer loop
        ///vertex 130.595413 123.542564 40.520229
        ///vertex 130.432938 122.731209 40.020565
        ///vertex 129.961243 123.003822 40.521114
        ///endloop
        ///endfacet
        ///facet normal -0.388898 0.604156 -0.695524
        ///outer loop
        ///vertex 129.642151 122.221832 40.0[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tricopter_stl {
            get {
                return ResourceManager.GetString("tricopter_stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap uavcanesc {
            get {
                object obj = ResourceManager.GetObject("uavcanesc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap wizardicon {
            get {
                object obj = ResourceManager.GetObject("wizardicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap wizardicon1 {
            get {
                object obj = ResourceManager.GetObject("wizardicon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap x8 {
            get {
                object obj = ResourceManager.GetObject("x8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap y6a {
            get {
                object obj = ResourceManager.GetObject("y6a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap y6b {
            get {
                object obj = ResourceManager.GetObject("y6b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
